service: hogeProject

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - 'dynamodb:*'
      Resource: '*'

package:
  exclude:
    - .git/**

functions:
  fooFunction:
    handler: handler.foo
    events:
      - http:
          path: foo
          method: get
  barFunction:
    handler: handler.bar
    events:
      - http:
          path: bar
          method: post

resources:
  Resources:
    HanjoAsReaderInventoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sample_table
        AttributeDefinitions:
          - AttributeName: hash_key
            AttributeType: S
          - AttributeName: range_key
            AttributeType: S            
        KeySchema:
          - AttributeName: hash_key
            KeyType: HASH
          - AttributeName: range_key
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    s3hosting:
      Type: 'AWS::S3::Bucket'
      Properties:
        WebsiteConfiguration:
          IndexDocument: index.html
        AccessControl: LogDeliveryWrite
        VersioningConfiguration:
          Status: Suspended
    UserPool:
      Type: "AWS::Cognito::UserPool"
      Properties:
        AdminCreateUserConfig:
            AllowAdminCreateUserOnly: false
            UnusedAccountValidityDays: 7
        AliasAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        EmailVerificationMessage: "Your verification code is {####}."
        EmailVerificationSubject: "Your verification code"
        MfaConfiguration: 'OFF'
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true
            RequireUppercase: true
        UserPoolName:
          Ref: AWS::StackName
        Schema:
          - AttributeDataType: "String"
            DeveloperOnlyAttribute: false
            Mutable: true
            Name: "email"
            StringAttributeConstraints:
              MaxLength: "2048"
              MinLength: "0"
            Required: true
          - AttributeDataType: "String"
            DeveloperOnlyAttribute: false
            Mutable: true
            Name: "custom-attr"
            StringAttributeConstraints:
              MaxLength: "2048"
              MinLength: "0"
            Required: false
        SmsAuthenticationMessage:  "Your authentication code is {####}."
        SmsVerificationMessage: "Your verification code is {####}."
        UserPoolTags:
          Name: 'Sample'
    UserPoolClient:
      Type: "AWS::Cognito::UserPoolClient"
      Properties:
          ClientName:
            Ref: AWS::StackName
          GenerateSecret: false
          ExplicitAuthFlows:
            - "ADMIN_NO_SRP_AUTH"
          ReadAttributes:
            - "email"
            - "custom:custom-attr"
          RefreshTokenValidity: 30
          UserPoolId:
            Ref: UserPool
          WriteAttributes:
            - "email"
            - "custom:custom-attr"
