service: my-service

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-northeast-1

resources:
  Resources:
    UserPool:
      Type: "AWS::Cognito::UserPool"
      Properties:
        AliasAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        UserPoolName:
          Ref: AWS::StackName
        Schema:
          - AttributeDataType: "String"
            DeveloperOnlyAttribute: false
            Mutable: true
            Name: "email"
            StringAttributeConstraints:
              MaxLength: "2048"
              MinLength: "0"
            Required: true
        UserPoolTags:
          Name: 'Sample'
    UserPoolClient:
      Type: "AWS::Cognito::UserPoolClient"
      Properties:
          ClientName:
            Ref: AWS::StackName
          GenerateSecret: false
          ExplicitAuthFlows:
            - "ADMIN_NO_SRP_AUTH"
          ReadAttributes:
            - "email"
          RefreshTokenValidity: 30
          UserPoolId:
            Ref: UserPool
          WriteAttributes:
            - "email"
            